@ABZPolicyWebApi_HostAddress = http://localhost:5007

GET {{ABZPolicyWebApi_HostAddress}}/api/policy/
Accept: application/json

###
GET {{ABZPolicyWebApi_HostAddress}}/api/policy/
Content-Type: application/json
{
  "policyNo": "12345678UT",
  "proposalNo": "P1234",
  "noClaimBonus": 100,
  "receiptNo": "12345",
  "receiptDate": "2024-12-19T10:15:47.247Z",
  "paymentMode": "C",
  "amount": 500
}
###
POST {{ABZPolicyWebApi_HostAddress}}/api/policy
Content-Type: application/json
{
  "policyNo": "++++++++++",
  "proposalNo": "----------",
  "noClaimBonus": 60000,
  "receiptNo": "ksglk",
  "receiptDate": "2024-12-21T12:59:33.118Z",
  "paymentMode": "U",
  "amount": 20000
}
###
GET {{ABZPolicyWebApi_HostAddress}}/api/policy/12345678UI
Accept: application/json
###
PUT {{ABZPolicyWebApi_HostAddress}}/api/policy/12345678UI
Content-Type: application/json
{
  "policyNo": "12345678UI",
  "prososalNo": "12345678SR",
  "noClaimBonus": 1000,
  "receiptNo": "12347",
  "receiptDate": "2024-12-19T10:15:47.247Z",
  "paymentMode": "C",
  "amount": 600
  
}
###
DELETE {{ABZPolicyWebApi_HostAddress}}/api/policy/12345678UA
Accept: application/json
###
GET {{ABZPolicyWebApi_HostAddress}}/api/policyAddon/
Accept: application/json
###
POST {{ABZPolicyWebApi_HostAddress}}/api/policyAddon
Content-Type: application/json
{
  "addonID": "Add3",
  "policyNo": "POL1234567",
  "amount": 100
}
###
PUT {{ABZPolicyWebApi_HostAddress}}/api/policyAddon/12345678UI/Add3
Content-Type: application/json
{
  "addonID": "Add3",
  "policyNo": "12345678UI",
  "amount": 600
}
###
DELETE {{ABZPolicyWebApi_HostAddress}}/api/policyAddon/12345678UI/Add3
Accept: application/json